In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a[[False,True,False,False]])

[2]


In [3]:
number=3
print(f"the number is number{}")

SyntaxError: f-string: empty expression not allowed (<ipython-input-3-798f68beff2c>, line 2)

In [4]:
import math
print(math.pow(2,10))

1024.0


In [5]:
X = np.array([[1,3],[4,6]])
y=(X.dot(5))
z=y.sum(axis=0)
print(z)
print(y)
print(X.size)


[25 45]
[[ 5 15]
 [20 30]]
4


In [18]:
s = np.array([[1,2,9],[3,4,0],[5,6,7],[1,6,4]])
s

array([[1, 2, 9],
       [3, 4, 0],
       [5, 6, 7],
       [1, 6, 4]])

In [13]:
import numpy as np
x1 = np.array([[1,2,3],[3,4,5],[6,7,8],[2,5,8]])
print(x1[0])


[1 2 3]
